### ISSUE TITLE
Argument of type '{ headless: boolean; }' is not assignable to parameter of type 'BrowserOptions'.

### ISSUE THREAD

**Issue by johnsickels** [flocasts/flagpole#21]
## Expected Behavior
I can pass the `{ headless: false }` option to the `.browser()` method to view a physical manifestation of the browser.

## Actual Behavior
Error message in VSCode
```
(property) headless: boolean
Argument of type '{ headless: boolean; }' is not assignable to parameter of type 'BrowserOptions'.
  Object literal may only specify known properties, and 'headless' does not exist in type 'BrowserOptions'.ts(2345)
```
Error message in terminal
```
Transpiling TypeScript to JavaScript...
src/headful.ts(8,32): error TS2345: Argument of type '{ headless: boolean; }' is not assignable to parameter of type 'BrowserOptions'.
  Object literal may only specify known properties, and 'headless' does not exist in type 'BrowserOptions'.
```

## Steps to Reproduce the Problem

```
import { Flagpole } from "flagpole";

const suite = Flagpole.suite("Browser Test with Head").base(
  "https://www.milesplit.com"
);

suite
  .browser("Homepage Loads", { headless: false })
  .open("/")
  .next(async (context) => {
    await context.exists("#content .coverStory");
  });
```

## Specifications

  - Version: 2.2.10
  - Platform: VSCode

**Comment by jasonbyrne** [comment]
I cannot reproduce this problem. 

Works fine on my machine with Node v12.13.0, TypeScript v3.7.2, VS Code 1.44.0 and Flagpole v2.2.10

**Comment by jasonbyrne** [comment]
`BrowserOptions extends LaunchOptions`

This is the line specifically. `LaunchOptions` is part of Puppeteer and it contains the `headless` property. The only other thing I could think to do is explicitly add it to `BrowserOptions` but we shouldn't need to (nor want to) duplicate properties from the abstract interface.

Maybe you have an old version of TypeScript that doesn't support this?

**Comment by jasonbyrne** [comment]
Still not sure why this was a thing, but I explicitly added it to the interface. It should be good now as far as TS at least. Closing this issue.
